### ISSUE TITLE
[Proposition] Page de contact

### ISSUE THREAD

**Issue by ghost** [laravel-france/starter-kit-fr#11]
En lien direct avec ce Pull Requests https://github.com/laravel-france/starter-kit-fr/issues/7, j'ai noté que la proposition de bestmomo était pertinente, cependant, en cas de non configuration de l'émail de l'administrateur, on indique de contacter l'administrateur pour régler le problème sur la page de contact !
Solution proposée :
- modification de la commande personnalisée d'installation pour proposer ce paramétrage.
- utilisation d'un système de journaux dans la base de données via l'ajout d'un contrôleur dans la partie frontend.

La seconde proposition permettant de tenir un journal pour l'inscription de nouveaux membres par exemple ou tout autre chose.

**Comment by TontonTof** [comment]
serait-il pas plus cohérent de dire que si l'email de l'admin n'est pas configurer, 
la page contact n'est pas visible ?

**Comment by ghost** [comment]
C'est aussi une idée, il faut dans ce cas là, modifier juste le layout du frontend.
Attendons d'autres avis sur la question.

**Comment by TontonTof** [comment]
je pense que ce genre de débat doit avoir lieu sur le forum

**Comment by ghost** [comment]
Ok pour moi, on reste dans le forum
