### ISSUE TITLE
Licence ?

### ISSUE THREAD

**Issue by JulienTant** [laravel-france/starter-kit-fr#4]
Le fait d'avoir une licence me gêne un peu, dans la mesure où ce projet est porté par Laravel France.

En effet, il était question pour moi que les projets soient portés par la communauté, dans une forme entièrement libre et ouverte, ou soumis à la license [MIT](http://opensource.org/licenses/MIT) avec en holder laravel.fr ; comme le sont les premiers projets ( le site, la doc, ... ) ou le Framework Laravel lui même.

Pour la mise en avant du travail fourni, une phrase dans la description du projet est tout à fait acceptable, à la condition de citer également le projet qui à inspirer ce dernier ( c'est une chaîne logique de justice. )

J'attends votre avis sur la question pour ce projet, et je m'en vais mettre à jour le guide sur les forums de Laravel France.

**Comment by TontonTof** [comment]
Bonjour AoSiX, 

j'ai mis une licence GPL parceque c'est la plus libre que je connaisse, sauf erreur de ma part, elle est entièrement libre https://fr.wikipedia.org/wiki/Licence_publique_g%C3%A9n%C3%A9rale_GNU.

pour moi aussi,  les projets sont portés par la communauté dans une forme entièrement libre et ouverte.

:)

**Comment by ghost** [comment]
Bonjour à tous,
Il en va de même pour moi, le travail est fait pour la communauté, n'étant pas trop au fait des différentes licences, je ne saurais pas quelle licence choisir. Cependant j'aurais pensé comme Christophe que la licence GPL était la plus permissive des licences libres.

**Comment by TontonTof** [comment]
Après vérification, il semble que la MIT soit encore plus permissive.

Carpentier Christophe
09.80.54.31.7206.51.49.07.18

Date: Sat, 8 Jun 2013 02:21:17 -0700
